(define (make-segment x1 y1 x2 y2)
    (cons (make-point x1 y1) (make-point x2 y2)))
(define (make-point x y)
    (cons x y))
(define (start-segment segment)
    (print-point (car segment)))
(define (end-segment segment)
    (print-point (cdr segment)))
(define (x-point point)
    (car point))
(define (y-point point)
    (cdr point))
(define (print-point p)
    (newline)
    (display "(")
    (display (x-point p))
    (display ", ")
    (display (y-point p))
    (display ")"))