(define (make-interval a b) (cons a b))
(define (upper-bound z)
    (let ((a (car z))
          (b (cdr z)))
    (max a b)))
(define (lower-bound z)
    (let ((a (car z))
          (b (cdr z)))
    (min a b)))