(define (install-polynomial-package)
    ;; ...
    (define (=zero? n)
        (define (poly? n)
            (eq? (type-tag n) 'polynomial ))
        (define (zero-terms? termlist) 
            (or (empty-termlist? termlist) 
                (and (=zero? (coeff (first-term termlist))) 
                    (zero-terms? (rest-terms termlist)))))
        (if (poly? n)
            (zero-terms? n)
            (zero? n)))
    ;; ...
    (put '=zero? 'polynomial =zero?)
'done )