(load "Chapter 2/2.3 Symbolic Data/set-binary.scm")
(define (lookup given-key set-of-records)
    (cond ((null? set-of-records) #f)
          ((< given-key (key (entry set-of-records)))
           (lookup given-key (left-branch set-of-records)))
          ((= given-key (key (entry set-of-records)))
           (entry set-of-records))
          ((> given-key (key (entry set-of-records)))
           (lookup given-key (right-branch set-of-records)))))