(define (list-of-values-left exps env)
    (if (no-operands? exps)
        '()
        (let ((left (eval (first-operands exps env))))
            (let ((right (list-of-values (rest-operands exps env))))
                (cons left right)))))

(define (list-of-values-right exps env)
    (if (no-operands? exps)
        '()
        (let ((right (list-of-values (rest-operands exps env))))
            (let ((left (eval (first-operands exps env))))
                (cons left right)))))