(define (list-of-values exps env)
    (if (no-operands? exps)
        '()
        (cons (eval (first-operands exps) env)
              (list-of-values (rest-operands exps) env))))

(define (eval-if exp env)
    (if (true? (eval (if-predicate exp) env))
        (eval (if-consequent exp) env)
        (eval (if-alternate exp) env)))