(load "Chapter 3/3.3 Modeling with Mutable Data/queue.scm")

(define q1 (make-queue))
(insert-queue! q1 'a )
; ((a) a)
(insert-queue! q1 'b )
; ((a b) b)
(delete-queue! q1)
; ((b) b)
(delete-queue! q1)
; (() b)

(define (print-queue queue)
    (define (print-helper front-queue)
        (if (null? front-queue)
            (newline)
            (begin (display (car front-queue))
                   (display " ")
                   (print-helper (cdr front-queue)))))
    (print-helper (car queue)))