(define (make-from-mag-ang r a)
    (define (dispatch op)
        (cond ((eq? 'real-part op) 
                (* r (cos a)))
              ((eq? 'imag-part op)
                (* r (sin a)))
              ((eq? 'magnitude op) r)
              ((eq? 'angle op) a)))
    dispatch)