(load "Chapter 2/2.2 Hierarchical Data and the Closure Property/exercise_2.19.scm")
(define (find-parity items even-odd)
    (define (find-iter-even a append-list)
        (if (null? (cdr a))
            (if (even? (car a))
                (append append-list (list (car a)))
                append-list) 
            (if (even? (car a))
                (find-iter-even (cdr a) (append append-list (list (car a))))
                (find-iter-even (cdr a) append-list))))
    (define (find-iter-odd a append-list)
        (if (null? (cdr a))
            (if (even? (car a))
                append-list 
                (append append-list (list (car a))))
            (if (not (even? (car a)))
                (find-iter-odd (cdr a) (append append-list (list (car a))))
                (find-iter-odd (cdr a) append-list))))
    (if (= even-odd 0)
        (find-iter-even items (list ))
        (find-iter-odd items (list ))))
(define (same-parity 1st-num . items)
    (if (even? 1st-num)
        (append (list 1st-num) (find-parity items 0))
        (append (list 1st-num) (find-parity items 1))))