(define (make-account balance password)
    (let ((secretpass password))
        (define (withdraw amount)
            (if (>= balance amount)
                (begin (set! balance (- balance amount))
                    balance)
                "Insufficient Funds"))   
        (define (deposit amount)
            (set! balance (+ balance amount))
            balance)
        (define (dispatch pass m)
            (if (eq? pass secretpass)
                (cond ((eq? m 'withdraw ) withdraw)
                      ((eq? m 'deposit ) deposit)
                      (else (error "Unknown request: MAKE-ACCOUNT" m)))
                (error "Incorrect Password")))
    dispatch))