(define (make-account balance password)
    (let ((secretpass password)
          (otherpass password))
        (define (withdraw amount)
            (if (>= balance amount)
                (begin (set! balance (- balance amount))
                    balance)
                "Insufficient Funds"))   
        (define (deposit amount)
            (set! balance (+ balance amount))
            balance)
        (define (dispatch pass m)
            (if (or (eq? pass secretpass) (eq? pass otherpass))
                (cond ((eq? m 'withdraw ) withdraw)
                      ((eq? m 'deposit ) deposit)
                      ((eq? m 'joint-account )
                        (lambda (account new-pass)
                            (set! otherpass new-pass)
                            account))
                      (else (error "Unknown request: MAKE-ACCOUNT" m)))
                (error "Incorrect Password")))
    dispatch))

(define (make-joint acc acc-pass new-pass)
    ((acc acc-pass 'joint-account) acc new-pass)))