(define (make-account balance password)
    (let ((secretpass password)
          (call-times 0))
        (define (withdraw amount)
            (if (>= balance amount)
                (begin (set! balance (- balance amount))
                    balance)
                "Insufficient Funds"))   
        (define (deposit amount)
            (set! balance (+ balance amount))
            balance)
        (define (call-proc input)
            (f input))
        (define (add-to-calls)
            (set! call-times (+ call-times 1)))
        (define (dispatch pass m)
            (if (eq? pass secretpass)
                (begin (set! call-times 0)
                    (cond ((eq? m 'withdraw ) withdraw)
                        ((eq? m 'deposit ) deposit)
                        (else (error "Unknown request: MAKE-ACCOUNT" m))))
                (begin (add-to-calls)
                       (if (> call-times 7)
                           call-the-cops
                           (error "Incorrect Password")))))
    dispatch))